# Generated by Django 4.2.30 on 2026-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='No Subject', help_text='Email subject with {{placeholder}} support', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(db_index=True, help_text='Unique template name', max_length=255, unique=True),
        ),
    ]
