# Generated by Django 4.2.30 on 2026-04-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_manager', '0002_emailtemplate_subject_alter_emailtemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='attachment_names',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment labels/names expected'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='has_attachments',
            field=models.BooleanField(default=False, help_text='Does this template require attachments?'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='has_global_attachment',
            field=models.BooleanField(default=False, help_text='Is the attachment identical for all recipients?'),
        ),
    ]
