# Generated by Django 4.2.30 on 2026-04-21 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_recipients', models.IntegerField(default=0, help_text='Total number of recipients in the CSV')),
                ('sent_count', models.IntegerField(default=0, help_text='Number of emails successfully sent')),
                ('failed_count', models.IntegerField(default=0, help_text='Number of emails that failed to send')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(help_text='The email template used for this dispatch', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_jobs', to='templates_manager.emailtemplate')),
            ],
            options={
                'verbose_name': 'Dispatch Job',
                'verbose_name_plural': 'Dispatch Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(help_text="Recipient's email address", max_length=254)),
                ('recipient_name', models.CharField(help_text="Recipient's display name", max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the email failed to send', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dispatch.dispatchjob')),
            ],
            options={
                'verbose_name': 'Dispatch Log',
                'verbose_name_plural': 'Dispatch Logs',
                'ordering': ['sent_at'],
            },
        ),
    ]
