# Generated by Django 4.2.30 on 2026-04-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['job', 'status'], name='dispatch_di_job_id_93ade4_idx'),
        ),
    ]
