# Generated by Django 4.2.30 on 2026-04-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_manager', '0002_emailtemplate_subject_alter_emailtemplate_name'),
        ('dispatch', '0002_alter_dispatchjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchjob',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The email template used for this dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_jobs', to='templates_manager.emailtemplate'),
        ),
    ]
